// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO7RnXF0crJ_t8SHRMNXKwbG2477ZcfTA',
    appId: '1:23340623187:android:7054148e8a1dee1ff8eda6',
    messagingSenderId: '23340623187',
    projectId: 'monumento-277103',
    databaseURL: 'https://monumento-277103.firebaseio.com',
    storageBucket: 'monumento-277103.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR3epTTYpjRyPxGO6PQvYl_N5DBi5HIwk',
    appId: '1:23340623187:ios:847d10c520899abff8eda6',
    messagingSenderId: '23340623187',
    projectId: 'monumento-277103',
    databaseURL: 'https://monumento-277103.firebaseio.com',
    storageBucket: 'monumento-277103.appspot.com',
    androidClientId: '23340623187-h9hqe2suq5cb4sbspmlqgen6d408q7ca.apps.googleusercontent.com',
    iosClientId: '23340623187-ovkddsst2i4s9o04dat95rrtb9fntu50.apps.googleusercontent.com',
    iosBundleId: 'com.jddeep.monumento',
  );
}
