# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
flutter_application_path = '../monumento_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'ios-monumento' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)

  # Pods for ios-monumento
pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Alamofire', '~> 4.7'
  pod 'GLTFSceneKitLoader'
 pod 'GLTFSceneKit'

end
