// android/app/load-env.gradle
def loadEnv() {
    def envFile = rootProject.file('../.env')
    if (envFile.exists()) {
        envFile.readLines().each { line ->
            if (!line.isEmpty() && !line.startsWith("#")) {
                def parts = line.split("=", 2)
                if (parts.length == 2) {
                    project.ext.set(parts[0], parts[1])
                }
            }
        }
    }
}

loadEnv()